import string
import random
import time

while True: 
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.00005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.00005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.00005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.00005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.005)
    print(randomLetter,end="")
    randomLetter = random.choice(string.ascii_letters)
    time.sleep(0.00005)
    print(randomLetter)